services:
  catalogDb:
    container_name: catalogDb
    environment:
      - POSTGRES_USER=postgras
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    
  basketDb:
    container_name: basketDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
        
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=maya
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogDb;Port=5432;Database=CatalogDb;User Id=postgres;Password=12345678;Include Error Detail=true
    depends_on:
      - catalogDb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/https:ro
        
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=maya
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=basketDb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basketDb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/https:ro
