services:
  catalogDb:
    container_name: catalogDb
    environment:
      - POSTGRES_USER=postgras
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=maya
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogDb;Port=5432;Database=CatalogDb;User Id=postgres;Password=12345678;Include Error Detail=true
    depends_on:
      - catalogDb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/https:ro